document.writeln("<div id=\'side-column\'>");
document.writeln("        <div class=\'side-mid\'>");
document.writeln("            <div class=\'side-mid-top\'>");
document.writeln("                <div>");
document.writeln("                    <em></em>");
document.writeln("                    <span>我的账户</span>");
document.writeln("                </div>");
document.writeln("                <img src=\'https://b2cstatic.baiyangwang.com/shop/common/05755058785008341.jpg\' alt=\'\'>");
document.writeln("            </div>");
document.writeln("            <div class=\'side-car\'>");
document.writeln("                <i></i>");
document.writeln("                <span>购物车</span>");
document.writeln("                <div class=\'numcar\'></div>");
document.writeln("            </div>");
document.writeln("            <span>");
document.writeln("                <div>");
document.writeln("                    <em></em>");
document.writeln("                    <span>在线联系</span>");
document.writeln("                </div>");
document.writeln("            </span>");
document.writeln("            <span>");
document.writeln("                <div>");
document.writeln("                    <em></em>");
document.writeln("                    <span>商品对比</span>");
document.writeln("                </div>");
document.writeln("            </span>");
document.writeln("        </div>");
document.writeln("        <span class=\'to-top\'>");
document.writeln("            <div>");
document.writeln("                <em></em>");
document.writeln("                <span>返回顶部</span>");
document.writeln("            </div>");
document.writeln("        </span>");
document.writeln("    </div>");
