document.writeln("<div id=\'foot\'>");
document.writeln("            <div class=\'content\'>");
document.writeln("                <img src=\'https://www.baiyangwang.com/templates/default/images/zhaoshang09_03.jpg\' alt=\'\'>");
document.writeln("                <div class=\'footer\'>");
document.writeln("                    <div class=\'foot-left\'>");
document.writeln("                        <img src=\'https://www.baiyangwang.com/data/upload/shop/common/logo.png\' alt=\'\'>");
document.writeln("                        <div class=\'footer-img\'>");
document.writeln("                            <span>关注我们</span>");
document.writeln("                            <div class=\'weibo\'>");
document.writeln("                                <img src=\'https://www.baiyangwang.com/templates/default/images/weibo02.png\' alt=\'\'>");
document.writeln("                                <div class=\'weibo-ewm\'>");
document.writeln("                                    <img src=\'https://www.baiyangwang.com/templates/default/images/weibo_qr.jpg\' alt=\'\'>");
document.writeln("                                    <em>");
document.writeln("                                        <i></i>");
document.writeln("                                    </em>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'weixin\'>");
document.writeln("                                <img src=\'https://www.baiyangwang.com/templates/default/images/weixin01.png\' alt=\'\'>");
document.writeln("                                <div class=\'weixin-ewm\'>");
document.writeln("                                    <img src=\'https://www.baiyangwang.com/templates/default/images/wexin_qr02.jpg\' alt=\'\'>");
document.writeln("                                    <em>");
document.writeln("                                        <i></i>");
document.writeln("                                    </em>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'foot-mid\'>");
document.writeln("                        <ul>");
document.writeln("                            <li>");
document.writeln("                                <p>新手指南</p>");
document.writeln("                                <span>购买流程</span>");
document.writeln("                                <span>支付方式</span>");
document.writeln("                                <span>通关税费</span>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <p>售后服务</p>");
document.writeln("                                <span>退货政策</span>");
document.writeln("                                <span>退货流程</span>");
document.writeln("                                <span>退款流程</span>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <p>物流配送</p>");
document.writeln("                                <span>配送方式</span>");
document.writeln("                                <span>物流跟踪</span>");
document.writeln("                                <span>自选物流</span>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <p>关于我们</p>");
document.writeln("                                <span>公司简介</span>");
document.writeln("                                <span>联系我们</span>");
document.writeln("                                <span>招商合作</span>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'foot-right\'>");
document.writeln("                        <div class=\'font-right-wx\'>");
document.writeln("                            <div>");
document.writeln("                                <img src=\'https://www.baiyangwang.com/templates/default/images/weixin-qr.jpg\' alt=\'\'>");
document.writeln("                            </div>");
document.writeln("                            <p>扫描进入微信商城</p>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'font-right-app\'>");
document.writeln("                            <div>");
document.writeln("                                <img src=\'https://www.baiyangwang.com/templates/default/images/app-qr.jpg\' alt=\'\'>");
document.writeln("                            </div>");
document.writeln("                            <p>扫描下载百洋APP</p>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'foot-wrapper\'>");
document.writeln("                    <ul class=\'tx\'>");
document.writeln("                        <li>友情链接申请</li>");
document.writeln("                        <li>求婚公司</li>");
document.writeln("                        <li>食疗养生</li>");
document.writeln("                        <li>九博精神健康网</li>");
document.writeln("                        <li>网上药店</li>");
document.writeln("                        <li>健康养生</li>");
document.writeln("                        <li>邻医网</li>");
document.writeln("                        <li>养生网</li>");
document.writeln("                        <li>红酒代理</li>");
document.writeln("                        <li>定制酒</li>");
document.writeln("                        <li>网上药店</li>");
document.writeln("                        <li>药房网</li>");
document.writeln("                        <li>中医中药大全网</li>");
document.writeln("                        <li>中医养生</li>");
document.writeln("                        <li>网店转让</li>");
document.writeln("                        <li>植发医院</li>");
document.writeln("                        <li>辟谷</li>");
document.writeln("                        <li>活力舒</li>");
document.writeln("                        <li>冬虫夏草</li>");
document.writeln("                        <li>藏药</li>");
document.writeln("                        <li>药房网</li>");
document.writeln("                    </ul>");
document.writeln("                    <p>首页 | 联系我们 </p>");
document.writeln("                    <p>版权所有 2007-2018 青岛百洋健康药房连锁有限公司 百洋健康 鲁ICP备09091598号 互联网药品信息服务资质证书编号 (鲁)-经营性-2017-0003 医疗器械经营许可证</p>");
document.writeln("                    <img src=\'https://www.baiyangwang.com/templates/default/images/jubao.jpg\' alt=\'\' class=\'foot-jubao\'>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");