document.writeln(" <div id=\'head\'>");
document.writeln("        <div class=\'tx content\'>");
document.writeln("            <div class=\'head-left\'>");
document.writeln("                <span class=\'username\'>您好，欢迎来到</span>");
document.writeln("                <span>百洋健康</span>");
document.writeln("                <span>");
document.writeln("                    <a href=\'###\' target=\'_blank\' id=\'login\'>[登入]</a>");
document.writeln("                </span>");
document.writeln("                <span>");
document.writeln("                    <a href=\'###\' target=\'_blank\' id=\'zhuce\'>[注册]</a>");
document.writeln("                </span>");
document.writeln("                <span>");
document.writeln("                    <a href=\'\' target=\'_self\' id=\'tuichu\'>[退出]</a>");
document.writeln("                </span>");
document.writeln("            </div>");
document.writeln("            <div class=\'head-right\'>");
document.writeln("                <ul>");
document.writeln("                    <p>");
document.writeln("                        <a href=\'###\' target=\'_blank\'>客服服务</a>");
document.writeln("                        <i class=\'iconfont iconxiajiantou1\'></i>");
document.writeln("                    </p>");
document.writeln("                    <li>帮助中心</li>");
document.writeln("                    <li>售后服务</li>");
document.writeln("                    <li>客服中心</li>");
document.writeln("                </ul>");
document.writeln("                <ul>");
document.writeln("                    <p>");
document.writeln("                        <a href=\'###\' target=\'_blank\'>我的收藏</a>");
document.writeln("                        <i class=\'iconfont iconxiajiantou1\'></i>");
document.writeln("                    </p>");
document.writeln("                    <li>商品收藏</li>");
document.writeln("                    <li>店铺收藏</li>");
document.writeln("                </ul>");
document.writeln("                <ul>");
document.writeln("                    <p>");
document.writeln("                        <a href=\'###\' target=\'_blank\'>我的订单</a>");
document.writeln("                        <i class=\'iconfont iconxiajiantou1\'></i>");
document.writeln("                    </p>");
document.writeln("                    <li>待付款订单</li>");
document.writeln("                    <li>待确认收货</li>");
document.writeln("                    <li>待评价交易</li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div id=\'header-wrap\'>");
document.writeln("        <div class=\'content tx\'>");
document.writeln("            <img src=\'https://b2cstatic.baiyangwang.com/shop/common/logo.png\' alt=\'\' class=\'logo\'>");
document.writeln("            <div id=\'header-input\'>");
document.writeln("                <div class=\'header-chaxun\'>");
document.writeln("                    <div class=\'chaxun-lishi\'>");
document.writeln("                        <div class=\'lishi-left tx\'>");
document.writeln("                            <div class=\'lishi-top\'>");
document.writeln("                                <span>历史记录</span>");
document.writeln("                                <a href=\'###\'>清除</a>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'chaxun-tx\'></div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'lishi-right tx\'>");
document.writeln("                        <div class=\'lishi-hot\'>");
document.writeln("                            热门搜索...");
document.writeln("                        </div>");
document.writeln("                        <ul class=\'tx\'>");
document.writeln("                            <li>日本药妆神器</li>");
document.writeln("                            <li>承善堂阿胶</li>");
document.writeln("                            <li>儿童长高推荐</li>");
document.writeln("                            <li>调节血脂</li>");
document.writeln("                            <li>蛋白粉</li>");
document.writeln("                            <li>补钙爆品</li>");
document.writeln("                            <li>眼部逆龄黑科技</li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'input-left\'>");
document.writeln("                    商品");
document.writeln("                    <img src=\'https://www.baiyangwang.com/templates/default/images/top-down.png\' alt=\'\'>");
document.writeln("                    <p>商品</p>");
document.writeln("                    <p>店铺</p>");
document.writeln("                </div>");
document.writeln("                <input type=\'text\' class=\'input-right\' placeholder=\'请输入您要搜索的商品关键字\'>");
document.writeln("                <input type=\'button\' class=\'input-btn\' value=\'搜索\'>");
document.writeln("                <ul class=\'tx keyword\'>");
document.writeln("                    <li>迪巧</li>");
document.writeln("                    <li>蛋白粉</li>");
document.writeln("                    <li>眼贴</li>");
document.writeln("                    <li>玻尿酸</li>");
document.writeln("                    <li>橄榄油</li>");
document.writeln("                    <li>麦片</li>");
document.writeln("                    <li>克奥妮斯</li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'header-div tx\'>");
document.writeln("                <div class=\'header-left\'>");
document.writeln("                    <i class=\'iconfont iconyiliaohangyedeICON-\'></i>");
document.writeln("                    <span>我的商城</span>");
document.writeln("                    <i class=\'iconfont iconxiajiantou2\'></i>");
document.writeln("                </div>");
document.writeln("                <div class=\'my-shoop\'>");
document.writeln("                    <div class=\'my-shoop-top\'>");
document.writeln("                        我的用户中心");
document.writeln("                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'my-shoop-mid\'>");
document.writeln("                        <ul class=\'tx\'>");
document.writeln("                            <li>站内消息(0)</li>");
document.writeln("                            <li>");
document.writeln("                                我的订单");
document.writeln("                                <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                            </li>");
document.writeln("                            <li>咨询回复(0)</li>");
document.writeln("                            <li>");
document.writeln("                                我的收藏");
document.writeln("                                <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                            </li>");
document.writeln("                            <li>代金券(0)</li>");
document.writeln("                            <li>");
document.writeln("                                我的积分");
document.writeln("                                <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'my-zuji\'>");
document.writeln("                        <div class=\'my-shoop-title\'>");
document.writeln("                            <span>最近浏览的商品</span>");
document.writeln("                            <a href=\'###\'>全部浏览历史</a>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'my-zuji-list tx\'>");
document.writeln("                            暂无商品");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'header-car tx\'>");
document.writeln("                <div class=\'header-right\'>");
document.writeln("                    <i class=\'iconfont iconiconset0308\'></i>");
document.writeln("                    <span>购物车结算</span>");
document.writeln("                    <span class=\'numcar\'>1</span>");
document.writeln("                    <i class=\'iconfont iconxiajiantou2\'></i>");
document.writeln("                </div>");
document.writeln("                <div class=\'header-car-list\'>");
document.writeln("                    <div class=\'car-top\'>");
document.writeln("                        最新加入的商品");
document.writeln("                    </div>");
document.writeln("                    <div class=\'car-list\'>");
document.writeln("                        <span class=\'null\'>您的购物车中暂无商品，赶快选择心爱的商品吧！</span>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'car-foot\'>");
document.writeln("                        <p>共");
document.writeln("                                <span class=\'headnumall\'>5</span>");
document.writeln("                                <span>种商品</span>");
document.writeln("                                <span>总计金额：</span>");
document.writeln("                                <span class=\'headmeyall\'>¥6582.00</span>");
document.writeln("                         </p>");
document.writeln("                        <div>结算购物车中的商品</div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln(" <div id=\'nav\'>");
document.writeln("        <div class=\'content tx\'>");
document.writeln("            <div class=\'nav-left\'>");
document.writeln("                <i class=\'iconfont icongengduo\'></i>");
document.writeln("                全部分类");
document.writeln("                <ul class=\'nav-title\'>");
document.writeln("                    <li>");
document.writeln("                        微量元素");
document.writeln("                        <div class=\'nav-title-tx\'>");
document.writeln("                            <div class=\'tx\'>");
document.writeln("                                <span>维生素B</span>");
document.writeln("                                <span>维生素C</span>");
document.writeln("                                <span>维生素D</span>");
document.writeln("                                <span>多种维生素</span>");
document.writeln("                                <span>钙</span>");
document.writeln("                                <dl>");
document.writeln("                                    <dt>");
document.writeln("                                        维生素");
document.writeln("                                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                                    </dt>");
document.writeln("                                    <dd>");
document.writeln("                                        <a href=\'###\'>维生素A</a>");
document.writeln("                                        <a href=\'###\'>维生素B</a>");
document.writeln("                                        <a href=\'###\'>维生素C</a>");
document.writeln("                                        <a href=\'###\'>维生素D</a>");
document.writeln("                                        <a href=\'###\'>维生素E</a>");
document.writeln("                                        <a href=\'###\'>维生素K</a>");
document.writeln("                                        <a href=\'###\'>多维维生素</a>");
document.writeln("                                    </dd>");
document.writeln("                                </dl>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        营养补充");
document.writeln("                        <div class=\'nav-title-tx\'>");
document.writeln("                            <div class=\'tx\'>");
document.writeln("                                <span>鱼油</span>");
document.writeln("                                <span>辅酶Q10</span>");
document.writeln("                                <span>益生菌</span>");
document.writeln("                                <span>褪黑素</span>");
document.writeln("                                <span>软骨素</span>");
document.writeln("                                <dl>");
document.writeln("                                    <dt>");
document.writeln("                                        维生素");
document.writeln("                                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                                    </dt>");
document.writeln("                                    <dd>");
document.writeln("                                        <a href=\'###\'>维生素A</a>");
document.writeln("                                        <a href=\'###\'>维生素B</a>");
document.writeln("                                        <a href=\'###\'>维生素C</a>");
document.writeln("                                        <a href=\'###\'>维生素D</a>");
document.writeln("                                        <a href=\'###\'>维生素E</a>");
document.writeln("                                        <a href=\'###\'>维生素K</a>");
document.writeln("                                        <a href=\'###\'>多维维生素</a>");
document.writeln("                                    </dd>");
document.writeln("                                </dl>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        健身运动");
document.writeln("                        <div class=\'nav-title-tx\'>");
document.writeln("                            <div class=\'tx\'>");
document.writeln("                                <span>乳清蛋白</span>");
document.writeln("                                <span>植物蛋白</span>");
document.writeln("                                <span>肌酸</span>");
document.writeln("                                <span>氨基酸</span>");
document.writeln("                                <span>代餐奶昔</span>");
document.writeln("                                <dl>");
document.writeln("                                    <dt>");
document.writeln("                                        维生素");
document.writeln("                                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                                    </dt>");
document.writeln("                                    <dd>");
document.writeln("                                        <a href=\'###\'>维生素A</a>");
document.writeln("                                        <a href=\'###\'>维生素B</a>");
document.writeln("                                        <a href=\'###\'>维生素C</a>");
document.writeln("                                        <a href=\'###\'>维生素D</a>");
document.writeln("                                        <a href=\'###\'>维生素E</a>");
document.writeln("                                        <a href=\'###\'>维生素K</a>");
document.writeln("                                        <a href=\'###\'>多维维生素</a>");
document.writeln("                                    </dd>");
document.writeln("                                </dl>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        美妆/个护");
document.writeln("                        <div class=\'nav-title-tx\'>");
document.writeln("                            <div class=\'tx\'>");
document.writeln("                                <span>维生素B</span>");
document.writeln("                                <span>维生素C</span>");
document.writeln("                                <span>维生素D</span>");
document.writeln("                                <span>多种维生素</span>");
document.writeln("                                <span>钙</span>");
document.writeln("                                <dl>");
document.writeln("                                    <dt>");
document.writeln("                                        维生素");
document.writeln("                                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                                    </dt>");
document.writeln("                                    <dd>");
document.writeln("                                        <a href=\'###\'>维生素A</a>");
document.writeln("                                        <a href=\'###\'>维生素B</a>");
document.writeln("                                        <a href=\'###\'>维生素C</a>");
document.writeln("                                        <a href=\'###\'>维生素D</a>");
document.writeln("                                        <a href=\'###\'>维生素E</a>");
document.writeln("                                        <a href=\'###\'>维生素K</a>");
document.writeln("                                        <a href=\'###\'>多维维生素</a>");
document.writeln("                                    </dd>");
document.writeln("                                </dl>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        妈咪宝贝");
document.writeln("                        <div class=\'nav-title-tx\'>");
document.writeln("                            <div class=\'tx\'>");
document.writeln("                                <span>维生素B</span>");
document.writeln("                                <span>维生素C</span>");
document.writeln("                                <span>维生素D</span>");
document.writeln("                                <span>多种维生素</span>");
document.writeln("                                <span>钙</span>");
document.writeln("                                <dl>");
document.writeln("                                    <dt>");
document.writeln("                                        维生素");
document.writeln("                                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                                    </dt>");
document.writeln("                                    <dd>");
document.writeln("                                        <a href=\'###\'>维生素A</a>");
document.writeln("                                        <a href=\'###\'>维生素B</a>");
document.writeln("                                        <a href=\'###\'>维生素C</a>");
document.writeln("                                        <a href=\'###\'>维生素D</a>");
document.writeln("                                        <a href=\'###\'>维生素E</a>");
document.writeln("                                        <a href=\'###\'>维生素K</a>");
document.writeln("                                        <a href=\'###\'>多维维生素</a>");
document.writeln("                                    </dd>");
document.writeln("                                </dl>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        家居/数码");
document.writeln("                        <div class=\'nav-title-tx\'>");
document.writeln("                            <div class=\'tx\'>");
document.writeln("                                <span>维生素B</span>");
document.writeln("                                <span>维生素C</span>");
document.writeln("                                <span>维生素D</span>");
document.writeln("                                <span>多种维生素</span>");
document.writeln("                                <span>钙</span>");
document.writeln("                                <dl>");
document.writeln("                                    <dt>");
document.writeln("                                        维生素");
document.writeln("                                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                                    </dt>");
document.writeln("                                    <dd>");
document.writeln("                                        <a href=\'###\'>维生素A</a>");
document.writeln("                                        <a href=\'###\'>维生素B</a>");
document.writeln("                                        <a href=\'###\'>维生素C</a>");
document.writeln("                                        <a href=\'###\'>维生素D</a>");
document.writeln("                                        <a href=\'###\'>维生素E</a>");
document.writeln("                                        <a href=\'###\'>维生素K</a>");
document.writeln("                                        <a href=\'###\'>多维维生素</a>");
document.writeln("                                    </dd>");
document.writeln("                                </dl>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        中西药品");
document.writeln("                        <div class=\'nav-title-tx\'>");
document.writeln("                            <div class=\'tx\'>");
document.writeln("                                <span>维生素B</span>");
document.writeln("                                <span>维生素C</span>");
document.writeln("                                <span>维生素D</span>");
document.writeln("                                <span>多种维生素</span>");
document.writeln("                                <span>钙</span>");
document.writeln("                                <dl>");
document.writeln("                                    <dt>");
document.writeln("                                        维生素");
document.writeln("                                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                                    </dt>");
document.writeln("                                    <dd>");
document.writeln("                                        <a href=\'###\'>维生素A</a>");
document.writeln("                                        <a href=\'###\'>维生素B</a>");
document.writeln("                                        <a href=\'###\'>维生素C</a>");
document.writeln("                                        <a href=\'###\'>维生素D</a>");
document.writeln("                                        <a href=\'###\'>维生素E</a>");
document.writeln("                                        <a href=\'###\'>维生素K</a>");
document.writeln("                                        <a href=\'###\'>多维维生素</a>");
document.writeln("                                    </dd>");
document.writeln("                                </dl>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        滋补保健");
document.writeln("                        <div class=\'nav-title-tx\'>");
document.writeln("                            <div class=\'tx\'>");
document.writeln("                                <span>维生素B</span>");
document.writeln("                                <span>维生素C</span>");
document.writeln("                                <span>维生素D</span>");
document.writeln("                                <span>多种维生素</span>");
document.writeln("                                <span>钙</span>");
document.writeln("                                <dl>");
document.writeln("                                    <dt>");
document.writeln("                                        维生素");
document.writeln("                                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                                    </dt>");
document.writeln("                                    <dd>");
document.writeln("                                        <a href=\'###\'>维生素A</a>");
document.writeln("                                        <a href=\'###\'>维生素B</a>");
document.writeln("                                        <a href=\'###\'>维生素C</a>");
document.writeln("                                        <a href=\'###\'>维生素D</a>");
document.writeln("                                        <a href=\'###\'>维生素E</a>");
document.writeln("                                        <a href=\'###\'>维生素K</a>");
document.writeln("                                        <a href=\'###\'>多维维生素</a>");
document.writeln("                                    </dd>");
document.writeln("                                </dl>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        性福生活");
document.writeln("                        <div class=\'nav-title-tx\'>");
document.writeln("                            <div class=\'tx\'>");
document.writeln("                                <span>维生素B</span>");
document.writeln("                                <span>维生素C</span>");
document.writeln("                                <span>维生素D</span>");
document.writeln("                                <span>多种维生素</span>");
document.writeln("                                <span>钙</span>");
document.writeln("                                <dl>");
document.writeln("                                    <dt>");
document.writeln("                                        维生素");
document.writeln("                                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                                    </dt>");
document.writeln("                                    <dd>");
document.writeln("                                        <a href=\'###\'>维生素A</a>");
document.writeln("                                        <a href=\'###\'>维生素B</a>");
document.writeln("                                        <a href=\'###\'>维生素C</a>");
document.writeln("                                        <a href=\'###\'>维生素D</a>");
document.writeln("                                        <a href=\'###\'>维生素E</a>");
document.writeln("                                        <a href=\'###\'>维生素K</a>");
document.writeln("                                        <a href=\'###\'>多维维生素</a>");
document.writeln("                                    </dd>");
document.writeln("                                </dl>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        环球美食");
document.writeln("                        <div class=\'nav-title-tx\'>");
document.writeln("                            <div class=\'tx\'>");
document.writeln("                                <span>维生素B</span>");
document.writeln("                                <span>维生素C</span>");
document.writeln("                                <span>维生素D</span>");
document.writeln("                                <span>多种维生素</span>");
document.writeln("                                <span>钙</span>");
document.writeln("                                <dl>");
document.writeln("                                    <dt>");
document.writeln("                                        维生素");
document.writeln("                                        <i class=\'iconfont iconarrow-right\'></i>");
document.writeln("                                    </dt>");
document.writeln("                                    <dd>");
document.writeln("                                        <a href=\'###\'>维生素A</a>");
document.writeln("                                        <a href=\'###\'>维生素B</a>");
document.writeln("                                        <a href=\'###\'>维生素C</a>");
document.writeln("                                        <a href=\'###\'>维生素D</a>");
document.writeln("                                        <a href=\'###\'>维生素E</a>");
document.writeln("                                        <a href=\'###\'>维生素K</a>");
document.writeln("                                        <a href=\'###\'>多维维生素</a>");
document.writeln("                                    </dd>");
document.writeln("                                </dl>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <ul class=\'menu\'>");
document.writeln("                <li>首页</li>");
document.writeln("                <li>维矿物质</li>");
document.writeln("                <li>营养补充</li>");
document.writeln("                <li>中西药品</li>");
document.writeln("                <li>知名美妆</li>");
document.writeln("                <li>免疫调节</li>");
document.writeln("                <li>庄园级橄榄油</li>");
document.writeln("                <li>有偿资讯</li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");